#!/usr/bin/env python

"""
    reduce_by_key.py
    Author: Yurui Mu
    
    key: valid key generated by mapper
    value: count
    """

import sys
import string

current_key = None
count = 0

# input comes from STDIN (stream data that goes to the program)
for line in sys.stdin:
    key, value = line.split('\t', 1)
    
    if current_key =='' and (key!=current_key):
        print"{0:s}\t{1:d}".format(current_key, count)
        count = 0
    elif current_key and (key != current_key):
        print "{0:s}\t{1:d}".format(current_key, count)
        count = 0
    count = count+1
    current_key = key

print "{0:s}\t{1:d}".format(key, count)